# La VM qui héberge Wiki.js (serveur web)
[web]
wiki ansible_host=10.0.50.50

# La VM qui héberge la base de données PostgreSQL
[db]
database ansible_host=10.0.50.51

# Variables communes à toutes les machines
[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/tp_cloud
# On passe par le Proxmox comme rebond pour atteindre le réseau privé 10.x
ansible_ssh_common_args='-J root@82.64.141.52:5007 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'